# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DramaEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brodcasting_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='item',
            name='drama_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.Drama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='drama_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Drama'),
        ),
        migrations.AddField(
            model_name='dramaepisode',
            name='drama_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Drama'),
        ),
        migrations.AddField(
            model_name='item',
            name='episode_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.DramaEpisode'),
        ),
        migrations.AddField(
            model_name='question',
            name='episode_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.DramaEpisode'),
        ),
    ]
