# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20170702_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
