# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_category_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/questions/')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemphoto',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='itemphoto',
            name='path',
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='upload',
            field=models.ImageField(default=None, upload_to='uploads/items/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='episode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.DramaEpisode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='drama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.Drama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='episode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.DramaEpisode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionphoto',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Question'),
        ),
    ]
