# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20170702_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.DramaEpisode'),
        ),
        migrations.AlterField(
            model_name='question',
            name='drama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Drama'),
        ),
        migrations.AlterField(
            model_name='question',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.DramaEpisode'),
        ),
    ]
