# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20170702_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='item',
        ),
        migrations.RemoveField(
            model_name='questionphoto',
            name='question',
        ),
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/items/'),
        ),
        migrations.AddField(
            model_name='question',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/questions/'),
        ),
        migrations.DeleteModel(
            name='ItemPhoto',
        ),
        migrations.DeleteModel(
            name='QuestionPhoto',
        ),
    ]
