# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20170702_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dramaepisode',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='item.Drama'),
        ),
        migrations.AlterField(
            model_name='item',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='item.Drama'),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='item.Item'),
        ),
        migrations.AlterField(
            model_name='question',
            name='drama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='item.Drama'),
        ),
        migrations.AlterField(
            model_name='question',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/questions/<built-in function id>/'),
        ),
    ]
