# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20170702_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/items/<built-in function id>'),
        ),
    ]
